<?php

/**
 * PlugindmBitLyUrlTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlugindmBitLyUrlTable extends myDoctrineTable
{

  public function findExpandedByShort($short)
  {
    return $this->createQuery('r')
    ->where('r.short = ?', $short)
    ->limit(1)
    ->select('r.expanded')
    ->fetchValue();
  }

  public function findShortByExpanded($expanded)
  {
    return $this->createQuery('r')
    ->where('r.expanded = ?', $expanded)
    ->limit(1)
    ->select('r.short')
    ->fetchValue();
  }

}